{% set name = "llama-index-core" %}
{% set version = "0.12.28" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_index_core-{{ version }}.tar.gz
  sha256: bf4a9697525e1294855d2df5c3a56b9720c185cde0eae2da713e7629c456c643

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - banks >=2.0.0,<3.0.0
    - eval-type-backport >=0.2.0,<0.3.0
    - filetype >=1.2.0,<2.0.0
    - typing_extensions >=4.5.0
    - pydantic >=2.8.0
    - wrapt
    - python >={{ python_min }},<4.0
    - sqlalchemy >=1.4.49
    - dataclasses-json
    - deprecated >=1.2.9.3
    - fsspec >=2023.5.0
    - httpx
    - nest-asyncio >=1.5.8,<2.0.0
    - nltk >3.8.1
    - numpy
    - tenacity >=8.2.0,!=8.4.0,<10.0.0
    - tiktoken >=0.3.3
    - typing-extensions >=4.5.0
    - typing_inspect >=0.8.0
    - requests >=2.31.0
    - aiohttp >=3.8.6,<4.0.0
    - networkx >=3.0
    - dirtyjson >=1.0.8,<2.0.0
    - tqdm >=4.66.1,<5.0.0
    - pillow >=9.0.0
    - pyyaml >=6.0.1
  run_constrained:
    - beautifulsoup4 >=4.12.2,<5.0.0
    - langchain >=0.0.303
    - gradientai >=1.4.0
    - asyncpg >=0.29.0,<0.30.0
    - pgvector >=0.3.6,<1.0.0
    - optimum >=1.13.2,<2.0.0
    - sentencepiece *
    - transformers >=4.33.1,<5.0.0
    - guidance >=0.0.64,<0.0.65
    - lm-format-enforcer >=0.4.3,<0.5.0
    - jsonpath-ng >=1.6.0,<2.0.0
    - rank-bm25 >=0.2.2,<0.3.0
    - scikit-learn *
    - spacy >=3.7.1,<4.0.0
    - psycopg2-binary >=2.9.9,<3.0.0

test:
  imports:
    - llama_index.core
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://llamaindex.ai
  dev_url: https://github.com/run-llama/llama_index/tree/main/llama-index-core
  summary: Interface between LLMs and your data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
